version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - .:/code
      - /code/node_modules
      - /code/lib
    ports:
      - 3000:3000
  db:
    image: mongo
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
    name: mongo-data
